### ISSUE TITLE
Robot Issue

### ISSUE THREAD

**Issue by Clivern** [gosilverback/pyumetric#12]
Issue Body

**Comment by v0xk** [comment]
Hello @Clivern, can you please do the following:

- Step 1.
- Step 2.

<details><summary>Details</summary>In response to <a href="https://github.com/silverbackhq/pyumetric/issues/12#issue-424531275">this</a>:<br/><br/><blockquote>Issue Body</blockquote>Instructions for interacting with me using issues and comments are available <a href="https://github.com/silverbackhq/svb-robot">here</a>. If you have questions or suggestions related to my behavior, <a href="https://github.com/silverbackhq/svb-robot/issues">please file an issue against me here</a></details>
